apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-r
  labels:
    component: frontend-r
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend-r
  template:
    metadata:
      labels:
        component: frontend-r
    spec:
      containers:
        - name: frontend-r
          image: bogdanp3trovic/frontend-r
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_LISTINGS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_LISTINGS_SERVICE_URL
                  name: frontend-configmap
            - name: REACT_APP_RESERVATIONS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_RESERVATIONS_SERVICE_URL
                  name: frontend-configmap
            - name: REACT_APP_IMAGES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  key: REACT_APP_IMAGES_SERVICE_URL
                  name: frontend-configmap
